### ISSUE TITLE
todo: environmentally friendly 2.0

### ISSUE THREAD

**Issue by pm065** [pm065/RepurposedRepurposedStructures#2]
- [x] flower forest temple overhaul
- [ ] swamp mineshaft overhaul
- [ ] carpenter and ceramist houses

**Comment by pm065** [comment]
The dungeons and mineshafts will have muddy floors, making navigation difficult. The rest will be made out of mud bricks.

**Comment by pm065** [comment]
A tiny chance will be added to swamp-related spawners of containing slabb feesh
